     VERSION    6                                                               
      DESCR   Lead sulfate - neutron RRRR                                       
    HSTRY  1 EXPEDT  V-MS-DOS  9-FEB-95 20:50:50 P PH        LA                 
    HSTRY  2 POWPREF V-MS-DOS  9-FEB-95 20:51: 7                                
    HSTRY  3 GENLES  V-MS-DOS  9-FEB-95 20:52:27 Sdsq=  .354E+06 S/E=  .639E-07 
    HSTRY  4 EXPEDT  V-MS-DOS  9-FEB-95 20:53:14             L  LO              
    HSTRY  5 GENLES  V-MS-DOS  9-FEB-95 20:54:29 Sdsq=  .147E+06 S/E=  .860E-03 
    HSTRY  6 EXPEDT  V-MS-DOS  9-FEB-95 20:56:11             LA  O              
    HSTRY  7 POWPREF V-MS-DOS  9-FEB-95 20:56:33                                
    HSTRY  8 GENLES  V-MS-DOS  9-FEB-95 20:58: 7 Sdsq=  .203E+05 S/E=  .651     
    HSTRY  9 EXPEDT  V-MS-DOS  9-FEB-95 20:59:11             L   O              
    HSTRY 10 POWPREF V-MS-DOS  9-FEB-95 20:59:18                                
    HSTRY 11 GENLES  V-MS-DOS  9-FEB-95 21: 1: 2 Sdsq=  .178E+05 S/E=  3.53     
    HSTRY 12 EXPEDT  V-MS-DOS  9-FEB-95 21: 3:52             L   O              
    HSTRY 13 POWPREF V-MS-DOS  9-FEB-95 21: 3:57                                
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  GNLS  RUN on  9-FEB-95 at 21: 5:12   Total cycles run  17       17855.        
  GNLS CDAT1  MXCY  5                                                           
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5805      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.40  108                                      
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21                                     
 AFAC  O_XAN   .090  .073  .069  .052  .047  .032  .008  .006  .003  .004       
 AFAC  S     6.9053 1.4679 5.203422.2151 1.4379  .2536 1.586356.1720  .8669 RHF 
 AFAC  S_    32.064 .2847         .53                                           
 AFAC  S_SIZ      1.47      1.27 1.85 1306                                      
 AFAC  S_XAB  15010  9402  4927 512.5 256.4                                     
 AFAC  S_XAN   .374 1.142  .370  .847  .319  .557  .110  .124  .068  .076       
 AFAC PB    31.0617  .690213.0637 2.357618.4420 8.6180 5.969647.257913.4118 RHF 
 AFAC PB_   203.973 .9401         .17                                           
 AFAC PB_SIZ      1.95     1.75  2.35  007                                      
 AFAC PB_XAB 221700143700 79840 42230 22760                                     
 AFAC PB_XAN -5.16115.595-4.59612.108-4.818 8.505-4.13310.102-1.910 6.930       
 EXPR  HTYP1  PNC                                                               
 EXPR  NATYP    3                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  PB          1      1.95     1.75  2.35  007                       
 EXPR ATYP 2  S           1      1.47      1.27 1.85 1306                       
 EXPR ATYP 3  O           3      1.09      0.89 1.40  108                       
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  6.185     for  31 variables                      
 REFN STATS  Cycle  17 There were  2918 observations. Total CHI**2 = 1.7855E+04 
CRS1    PNAM  pbso4                                                             
CRS1   NATOM    5                                                               
CRS1  ABC     8.472792  5.393243  6.953462    Y    0                            
CRS1  ABCSIG   .000226   .000149   .000194                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG     .0000     .0000     .0000                                      
CRS1  AT  1A  PB         .187433   .250000   .167074  1.000000PB1        4 000  
CRS1  AT  1B   .022996                                                    I XU  
CRS1  AT  2A  S          .066682   .250000   .684283  1.000000S2         4 000  
CRS1  AT  2B   .010946                                                    I XU  
CRS1  AT  3A  O         -.092399   .250000   .595187  1.000000O3         4 000  
CRS1  AT  3B   .028377                                                    I XU  
CRS1  AT  4A  O          .193982   .250000   .543155  1.000000O4         4 000  
CRS1  AT  4B   .022718                                                    I XU  
CRS1  AT  5A  O          .081047   .026986   .808873  1.000000O5         8 000  
CRS1  AT  5B   .021932                                                    I XU  
CRS1  CELVOL   317.744      .024                                                
CRS1  SG SYM  P n m a                                                           
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      2   12    .01000    0YYYNNNYNNNNNNNNNNNNN                       
HAP1 1PRCF 1    .232295E+03   -.659301E+03    .754334E+03    .000000E+00        
HAP1 1PRCF 2    .000000E+00    .000000E+00    .294778E+02    .000000E+00        
HAP1 1PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP1 1PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HST  1  HFIL  ..\data\pbso4_n.raw                                               
HST  1  HNAM  10.0    0.05    155.9   CPD RRRR   PbSO4 1.909A neutron data   8.8
HST  1  IFIL  ..\parm\inst_d1a.prm                                              
HST  1 BANK     1                                                               
HST  1 BIGFO    .000000E+00                                                     
HST  1 CHANS         0         1      2918  54239232      2919    1             
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    F                  
HST  1 ICONR  1.909000  0.000000      -7.3         0                            
HST  1 ICONS 1.9090000  .0000000  -2.04189    Z    0    .00000    0    .50000   
HST  1 MAXRF    9                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF   205     .9757    N    Y                                           
HST  1 TRNGE  10.00000 155.85000                                                
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     6    6    Y    0    Y                                           
HST  1BAKGD1    .231840E+03   -.497718E+01   -.570163E+02    .777156E+00        
HST  1BAKGD2    .103864E+02   -.374857E-01                                      
HST  1CHI       0.0000                                                          
HST  1EXC  1      .000      .000                                                
HST  1EXC  2   156.000  1000.000                                                
HST  1HSCALE     46471.        Y    0                                           
HST  1I HEAD  DUMMY INCIDENT SPECTRUM FOR DIFFRACTOMETER D1A                    
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1MNREF     0    1.0000                                                     
HST  1OMEGA     0.0000                                                          
HST  1PHI       0.0000                                                          
HST  1PRCF1     1    6      0.01                                                
HST  1PRCF11   0.354031E+03  -0.760404E+03   0.651592E+03   0.000000E+00        
HST  1PRCF12   0.000000E+00   0.000000E+00                                      
HST  1PRCF2     2    6      0.01                                                
HST  1PRCF21   0.354031E+03  -0.760404E+03   0.651592E+03   0.000000E+00        
HST  1PRCF22   0.000000E+00   0.000000E+00                                      
ZZZZZZZZZZZZ  Last EXP file record                                              
    HSTRY 14 GENLES  V-MS-DOS  9-FEB-95 21: 4:58 Sdsq=  .179E+05 S/E=  3.71     
