      SUBROUTINE MDCALC(MDVAL,MDAXIS,G,NUNIQ,UNIQ,MDCORR)

      INTEGER*4 NUNIQ
      REAL*4 MDVAL,MDAXIS(0:2),UNIQ(0:3*NUNIQ-1),G(3,3),MDCORR
      REAL*4 SUMMD

      SUMMD = FLOAT(NUNIQ)
      IF ( MDVAL .NE. 1.0) THEN
        SUMMD = 0.
        DA = SQRT(PRODVMV(MDAXIS,G,MDAXIS))
        DO I=0,NUNIQ-1
          DB = SQRT(PRODVMV(UNIQ(3*I),G,UNIQ(3*I)))
          CA = PRODVMV(MDAXIS,G,UNIQ(3*I))/(DA*DB)
          CALL DOLLASE(CA,MDVAL,CORR)
          SUMMD = SUMMD+CORR
        END DO
      END IF
      MDCORR = SUMMD/FLOAT(NUNIQ)
      RETURN
      END
