# -*- coding: utf-8 -*-
#makeTutorial.py
########### SVN repository information ###################
# $Date: $
# $Author: toby $
# $Revision: 3167 $
# $URL: $
# $Id: $
########### SVN repository information ###################
'''
*makeTutorial: Make Tutorial Web Page*
---------------------------------------------

Creates an HTML page (``GSASII/help/Tutorials.html``) listing all the tutorials in
:data:`GSASIIctrlGUI.tutorialIndex`. Run this after adding a new tutorial to that
index.
'''

from __future__ import print_function
import os
import GSASIIpath

if __name__ == '__main__':
    GSASIIpath.SetBinaryPath()
    import GSASIIctrlGUI as G2G
    G2BaseURL = G2G.G2BaseURL
    tutorialIndex = G2G.tutorialIndex
    tutURL = G2BaseURL +'/Tutorials'
    outname = os.path.join(GSASIIpath.path2GSAS2,'help','Tutorials.html')

    dirList = [l[0] for l in tutorialIndex if len(l) == 3]

    # loop through directories in Tutorials repository
    dirs = [d[:-1] for d in GSASIIpath.svnList(tutURL,False).split('\n') if d and d[-1] == '/']    
    for d in dirs:
        if d not in dirList: print(u"makeTutorial: Listed tutorial is missing: "+d)

    #import sys
    #out = sys.stdout
    out = open(outname,'w')
    print('<!-- Do not edit this file. It is created by makeTutorial.py from info in GSASIIctrlGUI.py --!>',file=out)
    print('<h2>List of GSAS-II tutorials</H2><UL>',file=out)
    print('''
    <p> A list of available tutorials appears below. Each tutorial is a
    web page that can be opened using the link below, but most tutorials also need
    to have example data files downloaded. This can also be done with links included below, 
    but it can be easier to access tutorials using 
    <b>Help/Tutorials</b> menu item.
    When this menu entry is used from inside GSAS-II (unless "browse tutorial on web" is selected),
    the data files are downloaded to a local directory and GSAS-II will start from that directory
    for most file open commands. 
    </p>''',file=out)

    for l in tutorialIndex:
        if len(l) == 1:
            print("</UL><h4>{}</H4><UL>".format(l[0]),file=out)
        else:
            pageURL = tutURL+'/'+l[0]+'/'+l[1]
            dataURL = tutURL+'/'+l[0]+'/data'
            suffix = ''
            if l[2][0] == ' ':
                suffix = ' <A href="#prereq">*</A>'
            if suffix: 
                print('<UL><LI><A href="{}">{}</A>{}'.format(pageURL,l[2].strip(),suffix),file=out)
            else:
                print('<LI><A href="{}">{}</A>'.format(pageURL,l[2].strip()),file=out)

            if GSASIIpath.svnList(dataURL,False):
                print(' [link: <A href="{}">Exercise files</A>].'.format(dataURL),file=out)
            else:
                print(' [No exercise files].',file=out)
            if suffix: print('</UL>',file=out)
    #        if l[2][0] == ' ':
    #            print(' (Note that this tutorial requires previous as prerequisite)',file=out)

    print('</UL>\n<A name=prereq>* Indented tutorials require the previous unindented tutorial as a prerequisite',file=out)
    out.close()
