     VERSION    6     Wed Nov 10 15:42:34 2010                                  
      DESCR   kryptonite                                                        
    HSTRY  1 EXPEDT  Win32  Oct 04 10:21:56 2011 P PH                           
    HSTRY  2 EXPTOOL  Win32  Oct 04 10:25:06 2011 P  A                          
    HSTRY  3 EXPEDT  Win32  Oct 04 10:25:55 2011             LA  O              
    HSTRY  4 POWPREF Win32  Oct 04 10:25:59 2011                                
    HSTRY  5 GENLES  Win32  Oct 04 10:26:04 2011 Sdsq= 0.120E+07 S/E= 0.150E-03 
    HSTRY  6 EXPEDT  Win32  Oct 04 10:26:27 2011             L  L               
    HSTRY  7 EXPEDT  Win32  Oct 04 10:28:02 2011             L   O              
    HSTRY  8 GENLES  Win32  Oct 04 10:28:10 2011 Sdsq= 0.690E+06 S/E= 0.128E-01 
    HSTRY  9 EXPEDT  Win32  Oct 04 10:29:34 2011             LA                 
    HSTRY 10 GENLES  Win32  Oct 04 10:29:42 2011 Sdsq= 0.149E+06 S/E= 0.453     
    HSTRY 11 EXPEDT  Win32  Oct 04 10:31:22 2011             LA                 
    HSTRY 12 POWPREF Win32  Oct 04 10:31:26 2011                                
    HSTRY 13 GENLES  Win32  Oct 04 10:31:47 2011 Sdsq= 0.770E+05 S/E= 0.167     
    HSTRY 14 EXPEDT  Win32  Feb 23 08:53:04 2012             L   O              
    HSTRY 15 POWPREF Win32  Feb 23 08:53:09 2012                                
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  GNLS  RUN on Feb 23 08:53:35 2012    Total cycles run  22       76967.        
  GNLS CDAT1  MXCY  5                                                           
  GNLS SHFTS      0.20      0.01                                                
 AFAC  B     2.054523.2185 1.3326 1.0210 1.097960.3498  .7068  .1403 -.1932 RHF 
 AFAC  B_     10.81   .53-.0213  767.                                           
 AFAC  B_SIZ      1.18      0.98 1.65   17                                      
 AFAC  B_XAB  129.8 76.85 38.45 6.194 4.592 23.90 64.50                         
 AFAC  B_XF1  0.019 0.014 0.009 0.001 0.000 0.026 0.012-0.001-0.001-0.001       
 AFAC  B_XF2  0.009 0.006 0.004 0.001 0.000 0.014 0.006 0.000 0.000 0.000       
 AFAC  H    .49300210.5109.32291226.1257.1401913.14236.04081057.7997.003038 SDS 
 AFAC  H_     1.008-.3741  20.6  19.2                                           
 AFAC  H_SIZ      0.98      0.78 1.20  118                                      
 AFAC  H_XAB  .6888 .6700 .6548 .6238 .6131 .7240 .6640                         
 AFAC  H_XF1     0.    0.    0.    0.    0.    0.    0.    0.    0.    0.       
 AFAC  H_XF2     0.    0.    0.    0.    0.    0.    0.    0.    0.    0.       
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5805      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 AFAC LI     1.1282 3.9546  .7508 1.0524  .617585.3905  .4653168.261  .0377 RHF 
 AFAC LI_     6.941 -.190        70.5                                           
 AFAC LI_SIZ      1.76      1.56 1.60   91                                      
 AFAC LI_XAB  14.32 9.193 5.496 2.268 2.061 2.510 7.990                         
 AFAC LI_XF1  0.002 0.002 0.001 0.000 0.000 0.004 0.001-0.001-0.001-0.001       
 AFAC LI_XF2  0.001 0.001 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000       
 AFAC NA     4.7626 3.2850 3.1736 8.8422 1.2674  .3136 1.1128129.424  .6760 RHF 
 AFAC NA_    22.990  .363        .530                                           
 AFAC NA_SIZ      2.10      1.91 2.00   15                                      
 AFAC NA_XAB   3761  2289  1157 112.2 57.34 6130. 1760.                         
 AFAC NA_XF1  0.230 0.186 0.135 0.036 0.022 0.280 0.167-0.003-0.003-0.004       
 AFAC NA_XF2  0.270 0.196 0.124 0.025 0.015 0.383 0.167 0.002 0.002 0.001       
 AFAC SI     6.2915 2.4386 3.035332.3337 1.9891  .6785 1.541081.6937 1.1407 RHF 
 AFAC SI_    28.086.41507        .171                                           
 AFAC SI_SIZ      1.52      1.32 2.00  112                                      
 AFAC SI_XAB   9456  5878  3047 304.7 151.8 15200 4560.                         
 AFAC SI_XF1  0.365 0.321 0.254 0.082 0.052 0.392 0.298-0.002-0.002-0.006       
 AFAC SI_XF2  0.692 0.508 0.330 0.070 0.043 0.962 0.438 0.006 0.005 0.004       
 EXPR  HTYP1  PXC                                                               
 EXPR  NATYP    6                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  LI          1      1.76      1.56 1.60   91                       
 EXPR ATYP 2  NA          1      2.10      1.91 2.00   15                       
 EXPR ATYP 3  B           3      1.18      0.98 1.65   17                       
 EXPR ATYP 4  SI          1      1.52      1.32 2.00  112                       
 EXPR ATYP 5  O           8      1.09      0.89 1.45   96 1.40                  
 EXPR ATYP 6  H           1      0.98      0.78 1.20  118                       
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  2.576     for   77 variables                     
 REFN RPOWD     0.0779    0.0625  29958  76967.        0.0000    0.0000     0   
 REFN STATS  Cycle  22 There were 29958 observations. Total CHI**2 = 7.6967E+04 
CRS1    PNAM  kryptonite                                                        
CRS1   NATOM   15                                                               
CRS1  ABC     6.763493 13.803014  7.689354    Y    0                            
CRS1  ABCSIG  0.000007  0.000018  0.000009                                      
CRS1  ANGLES   90.0000  124.0869   90.0000                                      
CRS1  ANGSIG    0.0000    0.0001    0.0000                                      
CRS1  AT  1A  LI        0.457076  0.199267  0.123318  1.000000Li1        4 000  
CRS1  AT  1B  0.013006                                                    I XU  
CRS1  AT  2A  NA        0.971759  0.991773  0.753874  1.000000Na1        4 000  
CRS1  AT  2B  0.020338                                                    I XU  
CRS1  AT  3A  B         0.237722  0.151291  0.686544  1.000000B1         4 000  
CRS1  AT  3B  0.008472                                                    I XU  
CRS1  AT  4A  B         0.686431  0.349234  0.418060  1.000000B2         4 000  
CRS1  AT  4B  0.007959                                                    I XU  
CRS1  AT  5A  B         0.531988  0.505392  0.784196  1.000000B3         4 000  
CRS1  AT  5B  0.009137                                                    I XU  
CRS1  AT  6A  SI        0.040592  0.752072  0.206292  1.000000Si1        4 000  
CRS1  AT  6B  0.006541                                                    I XU  
CRS1  AT  7A  O         0.810535  0.720823  0.977766  1.000000O1         4 000  
CRS1  AT  7B  0.005538                                                    I XU  
CRS1  AT  8A  O         0.271132  0.784126  0.207597  1.000000O2         4 000  
CRS1  AT  8B  0.005813                                                    I XU  
CRS1  AT  9A  O         0.965180  0.847175  0.286680  1.000000O3         4 000  
CRS1  AT  9B  0.004678                                                    I XU  
CRS1  AT 10A  O         0.123234  0.658490  0.359314  1.000000O4         4 000  
CRS1  AT 10B  0.004280                                                    I XU  
CRS1  AT 11A  O         0.748499  0.550908  0.875034  1.000000O5         4 000  
CRS1  AT 11B  0.006543                                                    I XU  
CRS1  AT 12A  O         0.682627  0.453255  0.355709  1.000000O6         4 000  
CRS1  AT 12B  0.006638                                                    I XU  
CRS1  AT 13A  O         0.543340  0.675466  0.615955  1.000000O7         4 000  
CRS1  AT 13B  0.002758                                                    I XU  
CRS1  AT 14A  O         0.524271  0.408250  0.832317  1.000000O8         4 000  
CRS1  AT 14B  0.011801                                                    I XU  
CRS1  AT 15A  H         0.699000  0.399300  0.936000  1.000000H1         4 000  
CRS1  AT 15B  0.095300                                                    I     
CRS1  CELVOL        594.517          0.001                                      
CRS1  CHMF 1  LI            1.00                                                
CRS1  CHMF 2  NA            1.00                                                
CRS1  CHMF 3  B             3.00                                                
CRS1  CHMF 4  SI            1.00                                                
CRS1  CHMF 5  O             8.00                                                
CRS1  CHMF 6  H             1.00                                                
CRS1  SG SYM  P 21/c                                                            
CRS1  SPAXIS   0.   1.   0.        0.   0.   0.   0.   0.   0.                  
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      3   19   0.00100    0NNNNYYNNNNYYNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 1PRCF 1   0.116300E+01  -0.126000E+00   0.630000E-01   0.000000E+00        
HAP1 1PRCF 2   0.599917E-01   0.656576E+01   0.110000E-02   0.110000E-02        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.160815E+01   0.125425E-01        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00                       
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  11bmb_6231.fxye                                                   
HST  1  HNAM  From jun10/11bmb_6231.mda processed @ 10-06-11 14:18              
HST  1  IFIL  11bmb_6231.prm                                                    
HST  1 BANK     1                                                               
HST  1 BIGFO   0.313725E+05                                                     
HST  1 CHANS      2663         1     29958  98551287     49497    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR 0.4135290    0.0000    0.0000               0.990    0     0.      
HST  1 ICONS 0.4135290    0.0000    0.0000               0.990    0     0.      
HST  1 IRAD     0                                                               
HST  1 MAXRF  174                                                               
HST  1 NEXC     2                                                               
HST  1 NFOBS 1688    0    0    0    0    0    0    0    0                       
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF  1689    0.7254    Y    Y                                           
HST  1 R-FAC 1688   0.03947   1.355598E+05                                      
HST  1 RPOWD    0.0779    0.0625  29958  76967.        0.0000    0.0000    0    
HST  1 TRNGE   3.16300  33.12000                                                
HST  1 WREXP    0.0486                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     9   12    Y    0    Y                                           
HST  1BAKGD1   0.144618E+03   0.153373E+03   0.252658E+03   0.230766E+03        
HST  1BAKGD2   0.118902E+03   0.118964E+03   0.129830E+03   0.124788E+03        
HST  1BAKGD3   0.127411E+03   0.142464E+03   0.131116E+03   0.132879E+03        
HST  1CHI       0.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  1     0.000     3.162                                                
HST  1EXC  2    33.121  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1FFANS1  LI           0.000     0.000   NN    0                            
HST  1FFANS2  NA           0.000     0.000   NN    0                            
HST  1FFANS3  B            0.000     0.000   NN    0                            
HST  1FFANS4  SI           0.000     0.000   NN    0                            
HST  1FFANS5  O            0.000     0.000   NN    0                            
HST  1FFANS6  H            0.000     0.000   NN    0                            
HST  1HSCALE     4.9409        Y    0                                           
HST  1I HEAD  11-BM profile SRM 660a (LaB6) fit (Feb 2009)                      
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1INAME   APS11BM                                                           
HST  1MNREF     0    1.0000                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000    Y                                                     
HST  1PHI       0.0000                                                          
HST  1PRCF1     3   19   0.00100                                                
HST  1PRCF11       1.163000      -0.126000       0.063000   0.000000E+00        
HST  1PRCF12       0.173000       0.000000       0.001100       0.001100        
HST  1PRCF13   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF14   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF15   0.000000E+00   0.000000E+00   0.000000E+00                       
HST  1RSP    0.0766 0.0748 0.0720 0.0546 0.0516 0.0470 0.0455 0.0456 0.0460     
HST  1RSPA   0.0716 0.0711 0.0711 0.0528 0.0519 0.0480 0.0461 0.0450 0.0458     
HST  1RSPTT   3.16  6.49  9.82 13.15 16.48 19.81 23.13 26.46 29.79 33.12        
HST  1RSPW   0.1033 0.0976 0.0894 0.0688 0.0647 0.0588 0.0574 0.0572 0.0575     
HST  1RSPWA  0.0938 0.0883 0.0867 0.0653 0.0651 0.0609 0.0591 0.0563 0.0575     
HST  1TRMNMX   1.00000   1.00000                                                
ZZZZZZZZZZZZ  Last EXP file record                                              
    HSTRY 16 GENLES  Win32  Feb 23 08:53:31 2012 Sdsq= 0.770E+05 S/E= 0.914E-01 
