      BLOCKDATA
C     SUB-PROGRAM 'BLOCKDATA' ...
C        INITIALIZES VARIABLES
C
C
      COMMON /UNIT1/ IUNITA
      COMMON /UNIT2/ IUNITB
      COMMON /UNIT4/ IUNITD
C
C
      DATA IUNITA/5/, IUNITB/6/, IUNITD/10/
C
      END
