     VERSION    6                                                               
      DESCR   Corundum, Magenitite & Zircon                                     
    HSTRY  1 EXPEDT  MS-DOS 1999-01-28T23:21:43  P PH        L   O              
    HSTRY  2 POWPREF MS-DOS 1999-01-28T23:21:51                                 
    HSTRY  3 GENLES  MS-DOS 1999-01-28T23:24:00  Sdsq=  .537E+06 S/E=  29.9     
    HSTRY  4 EXPEDT  MS-DOS 1999-01-28T23:26:01              L   O              
    HSTRY  5 GENLES  MS-DOS 1999-01-28T23:28:04  Sdsq=  .108E+06 S/E=  135.     
    HSTRY  6 EXPEDT  MS-DOS 1999-01-29T08:37:24              L   O              
  GNLS  RUN on 1999-01-29T08:40:58     Total cycles run   9       52448.        
  GNLS CDAT1  MXCY  3                                                           
  GNLS SHFTS      2.36       .10                                                
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5805      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.40   96                                      
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21                                     
 AFAC  O_XAN   .090  .073  .069  .052  .047  .032  .008  .006  .003  .004       
 AFAC AL     6.4202 3.0387 1.9002  .7426 1.593631.5472 1.964685.0886 1.1151 RHF 
 AFAC AL_    26.982 .3449        .231                                           
 AFAC AL_SIZ      1.60      1.43 2.05  109                                      
 AFAC AL_XAB   7074  4368  2249 225.8 113.7                                     
 AFAC AL_XAN   .318  .522  .269  .381  .204  .246  .056  .052  .032  .031       
 AFAC FE    11.7695 4.7611 7.3573  .3072 3.522215.3535 2.304576.8805 1.0369 RHF 
 AFAC FE_    55.847  .954        2.56                                           
 AFAC FE_SIZ      1.47      1.27 2.15   32                                      
 AFAC FE_XAB  10490  6528 28230  3500  1791                                     
 AFAC FE_XAN -1.339  .764-2.095  .566-1.179 3.204  .301  .845  .244  .545       
 AFAC SI     6.2915 2.4386 3.035332.3337 1.9891  .6785 1.541081.6937 1.1407 RHF 
 AFAC SI_    28.086 .4149        .171                                           
 AFAC SI_SIZ      1.52      1.32 2.00  112                                      
 AFAC SI_XAB   9456  5878  3047 304.7 151.8                                     
 AFAC SI_XAN   .355  .693  .311  .509  .244  .330  .072  .071  .042  .043       
 AFAC ZR    17.87651.2761810.948011.91605.41732.1176223.6572187.66272.06929*RHF 
 AFAC ZR_     91.22  .716        .185                                           
 AFAC ZR_SIZ      1.80      1.60 2.25   95                                      
 AFAC ZR_XAB  60370 38440 20710 11390  8367                                     
 AFAC ZR_XAN   .007 4.422 -.061 3.329 -.314 2.245-2.965  .560 -.639 2.630       
 EXPR  HTYP1  PNT  PNT  PNT  PNT                                                
 EXPR  NATYP    5                                                               
 EXPR  NHST     4                                                               
 EXPR ATYP 1  AL          1      1.60      1.43 2.05  109                       
 EXPR ATYP 2  O           3      1.09      0.89 1.40   96                       
 EXPR ATYP 3  FE          2      1.47      1.27 2.15   32                       
 EXPR ATYP 4  ZR          1      1.80      1.60 2.25   95                       
 EXPR ATYP 5  SI          1      1.52      1.32 2.00  112                       
 EXPR NPHAS     1    1    1    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  2.861     for  85 variables                      
 REFN STATS  Cycle   9 There were 18415 observations. Total CHI**2 = 5.2448E+04 
CRS1    PNAM  corundum                                                          
CRS1   NATOM    2                                                               
CRS1  ABC     4.757450  4.757464 12.987070                                      
CRS1  ABCSIG   .000082   .000082   .000313                                      
CRS1  ANGLES   90.0000   90.0000  120.0000                                      
CRS1  ANGSIG     .0000     .0000     .0000                                      
CRS1  AT  1A  AL         .000000   .000000   .352280  1.000000AL1       12 000  
CRS1  AT  1B   .004053                                                    I     
CRS1  AT  2A  O          .306400   .000000   .250000  1.000000O2        18 000  
CRS1  AT  2B   .004179                                                    I     
CRS1  CELVOL   254.561      .010                                                
CRS1  ODF                                                                       
CRS1  SG SYM  R -3 c                                                            
CRS1  SPAXIS    0    0    1                                                     
CRS2    PNAM  Magnetite                                                         
CRS2   NATOM    3                                                               
CRS2  ABC     8.392599  8.392599  8.392599                                      
CRS2  ABCSIG   .000318   .000318   .000318                                      
CRS2  ANGLES   90.0000   90.0000   90.0000                                      
CRS2  ANGSIG     .0000     .0000     .0000                                      
CRS2  AT  1A  FE         .125000   .125000   .125000  1.000000FE1        8 000  
CRS2  AT  1B   .002026                                                    I     
CRS2  AT  2A  FE         .500000   .500000   .500000  1.000000FE2       16 000  
CRS2  AT  2B   .010892                                                    I     
CRS2  AT  3A  O          .254800   .254800   .254800  1.000000O3        32 000  
CRS2  AT  3B   .008232                                                    I     
CRS2  CELVOL   591.139      .067                                                
CRS2  ODF       0    0    0 NNNN    0    0     .0000     .0000     .0000        
CRS2  ODF 1A   4  0  1   6  0  1   8  0  1  10  0  1                            
CRS2  ODF 1B     -.641     2.564     2.464     3.927                            
CRS2  ODF 1C .1220E+00 .1239E+00 .9313E-01 .1887E+00                            
CRS2  SG SYM  F d 3 m                                                           
CRS2  SPAXIS   1.   1.   1.        0.   0.   0.   0.   0.   0.                  
CRS3    PNAM  Zircon                                                            
CRS3   NATOM    3                                                               
CRS3  ABC     6.604866  6.604866  5.993814                                      
CRS3  ABCSIG   .000162   .000162   .000377                                      
CRS3  ANGLES   90.0000   90.0000   90.0000                                      
CRS3  ANGSIG     .0000     .0000     .0000                                      
CRS3  AT  1A  ZR         .000000   .750000   .125000  1.000000ZR1        4 000  
CRS3  AT  1B   .003546                                                    I     
CRS3  AT  2A  SI         .000000   .250000   .375000  1.000000SI2        4 000  
CRS3  AT  2B   .003926                                                    I     
CRS3  AT  3A  O          .000000   .066000   .195100  1.000000O3        16 000  
CRS3  AT  3B   .006332                                                    I     
CRS3  CELVOL   261.476      .019                                                
CRS3  ODF      10   11    0 NNNY    0    0     .0000     .0000     .0000        
CRS3  ODF 1A   2  0  0   4  0  0   4  0  4   6  0  0   6  0  4   8  0  0        
CRS3  ODF 1B     -.272      .180      .150     -.001     -.018     -.273        
CRS3  ODF 1C .2517E-01 .3239E-01 .3434E-01 .6927E-01 .5250E-01 .9940E-01        
CRS3  ODF 2A   8  0  4   8  0  8  10  0  0  10  0  4  10  0  8                  
CRS3  ODF 2B      .189     -.219      .503     -.890      .201                  
CRS3  ODF 2C .6374E-01 .8026E-01 .1077E+00 .8630E-01 .7758E-01                  
CRS3  SG SYM  I 41/a m d                                                        
CRS3  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      .66501        Y    0                                           
HAP1 1PRCF      1   12    .01000    0NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 1PRCF 1    .000000E+00    .500000E+01    .281732E-01    .712807E-02        
HAP1 1PRCF 2    .000000E+00    .517212E+02    .000000E+00    .733195E+01        
HAP1 1PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP1 1PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP1 2 ZONE     0    0    0    0                                                
HAP1 2EXTPOW    0.00000E+00    N    0                                           
HAP1 2NAXIS     1                                                               
HAP1 2PHSFR      .66501        Y    0                                           
HAP1 2PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 2PRCF 1    .000000E+00    .500000E+01    .275585E-01    .728077E-02        
HAP1 2PRCF 2    .000000E+00    .987096E+02    .000000E+00    .782206E+01        
HAP1 2PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP1 2PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP1 3 ZONE     0    0    0    0                                                
HAP1 3EXTPOW    0.00000E+00    N    0                                           
HAP1 3NAXIS     1                                                               
HAP1 3PHSFR      .66501        Y    0                                           
HAP1 3PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 3PRCF 1    .000000E+00    .500000E+01    .288849E-01    .351727E-02        
HAP1 3PRCF 2    .000000E+00    .785518E+02    .000000E+00    .131846E+02        
HAP1 3PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP1 3PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP1 4 ZONE     0    0    0    0                                                
HAP1 4EXTPOW    0.00000E+00    N    0                                           
HAP1 4NAXIS     1                                                               
HAP1 4PHSFR      .66501        Y    0                                           
HAP1 4PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 4PRCF 1    .000000E+00    .500000E+01    .286571E-01    .123176E-01        
HAP1 4PRCF 2    .000000E+00    .192689E+03    .000000E+00    .140580E+02        
HAP1 4PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP1 4PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP2 1 ZONE     0    0    0    0                                                
HAP2 1EXTPOW    0.00000E+00    N    0                                           
HAP2 1NAXIS     1                                                               
HAP2 1PHSFR      .81204E-01    Y    0                                           
HAP2 1PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP2 1PRCF 1    .000000E+00    .500000E+01    .281732E-01    .712807E-02        
HAP2 1PRCF 2    .000000E+00    .542872E+02    .000000E+00    .748486E+01        
HAP2 1PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP2 1PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP2 2 ZONE     0    0    0    0                                                
HAP2 2EXTPOW    0.00000E+00    N    0                                           
HAP2 2NAXIS     1                                                               
HAP2 2PHSFR      .81204E-01    Y    0                                           
HAP2 2PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP2 2PRCF 1    .000000E+00    .500000E+01    .275585E-01    .728077E-02        
HAP2 2PRCF 2    .000000E+00    .103040E+03    .000000E+00    .790794E+01        
HAP2 2PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP2 2PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP2 3 ZONE     0    0    0    0                                                
HAP2 3EXTPOW    0.00000E+00    N    0                                           
HAP2 3NAXIS     1                                                               
HAP2 3PHSFR      .81204E-01    Y    0                                           
HAP2 3PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP2 3PRCF 1    .000000E+00    .500000E+01    .288849E-01    .351727E-02        
HAP2 3PRCF 2    .000000E+00    .755476E+02    .000000E+00    .129546E+02        
HAP2 3PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP2 3PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP2 4 ZONE     0    0    0    0                                                
HAP2 4EXTPOW    0.00000E+00    N    0                                           
HAP2 4NAXIS     1                                                               
HAP2 4PHSFR      .81204E-01    Y    0                                           
HAP2 4PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP2 4PRCF 1    .000000E+00    .500000E+01    .286571E-01    .123176E-01        
HAP2 4PRCF 2    .000000E+00    .179895E+03    .000000E+00    .135407E+02        
HAP2 4PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP2 4PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP3 1 ZONE     0    0    0    0                                                
HAP3 1EXTPOW    0.00000E+00    N    0                                           
HAP3 1NAXIS     1                                                               
HAP3 1PHSFR      .28535        Y    0                                           
HAP3 1PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP3 1PRCF 1    .000000E+00    .500000E+01    .281732E-01    .712807E-02        
HAP3 1PRCF 2    .000000E+00    .916980E+02    .000000E+00    .767354E+01        
HAP3 1PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP3 1PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP3 2 ZONE     0    0    0    0                                                
HAP3 2EXTPOW    0.00000E+00    N    0                                           
HAP3 2NAXIS     1                                                               
HAP3 2PHSFR      .28535        Y    0                                           
HAP3 2PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP3 2PRCF 1    .000000E+00    .500000E+01    .275585E-01    .728077E-02        
HAP3 2PRCF 2    .000000E+00    .148472E+03    .000000E+00    .834208E+01        
HAP3 2PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP3 2PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP3 3 ZONE     0    0    0    0                                                
HAP3 3EXTPOW    0.00000E+00    N    0                                           
HAP3 3NAXIS     1                                                               
HAP3 3PHSFR      .28535        Y    0                                           
HAP3 3PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP3 3PRCF 1    .000000E+00    .500000E+01    .288849E-01    .351727E-02        
HAP3 3PRCF 2    .000000E+00    .104047E+03    .000000E+00    .136382E+02        
HAP3 3PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP3 3PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HAP3 4 ZONE     0    0    0    0                                                
HAP3 4EXTPOW    0.00000E+00    N    0                                           
HAP3 4NAXIS     1                                                               
HAP3 4PHSFR      .28535        Y    0                                           
HAP3 4PRCF      1   12   0.01000     NNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP3 4PRCF 1    .000000E+00    .500000E+01    .286571E-01    .123176E-01        
HAP3 4PRCF 2    .000000E+00    .227638E+03    .000000E+00    .148914E+02        
HAP3 4PRCF 3    .000000E+00    .000000E+00    .000000E+00    .000000E+00        
HAP3 4PREFO1  1.000000  1.000000   .000000   .000000  1.000000   NN    0    0   
HST  1  HFIL  6731.dat                                                          
HST  1  HNAM  ROUND ROBIN SAMPLE 4                                              
HST  1  IFIL  I22JAN99.PRM                                                      
HST  1 BANK     1                                                               
HST  1 BIGFO    .631789E+02                                                     
HST  1 CHANS      3359         1      4190 161969914      7550    1             
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    T                  
HST  1 ICONR   5074.11     -2.10      3.29                                      
HST  1 ICONS   5074.11     -2.10      3.29                                      
HST  1 MAXRF   48                                                               
HST  1 NEXC     2                                                               
HST  1 NPHAS    1    1    1    0    0    0    0    0    0                       
HST  1 NREF   469     .5903    Y    Y                                           
HST  1 R-FAC N-obs  459 R-factor  .06262                                        
HST  1 RPOWD     .0549     .0374                                                
HST  1 TRNGE   2.99958  23.99368                                                
HST  1 WREXP     .0369                                                          
HST  1ABSCOR   -.693676E-01    .000000E+00    Y    0    0                       
HST  1BAKGD     7   10    Y    0    Y    0000000000000                          
HST  1BAKGD1    .467728E-01    .407552E-01    .424192E-01    .375369E-01        
HST  1BAKGD2    .526248E-01    .490371E-01    .546214E-01    .583638E-01        
HST  1BAKGD3    .587986E-01    .699922E-01                                      
HST  1BNKNAM  PLUS_153                                                          
HST  1BNKPAR    1.2495   151.000      25.0     1.321     30.48   16   73        
HST  1BNKTC1 5074.60 5070.80 5067.00 5063.10 5059.20 5055.20 5051.20 5047.20    
HST  1BNKTC2 5043.10 5039.00 5034.90 5030.70 5026.50 5022.20 5017.90 5013.60    
HST  1CHI      90.0000                                                          
HST  1EXC  1      .000     2.998                                                
HST  1EXC  2    24.000  1000.000                                                
HST  1HSCALE     1.0000        N    0                                           
HST  1I HEAD  CALIBRATION V/NB                                                  
HST  1I ITYP    4    1.0000   23.9997     40986                                 
HST  1ICOFF1    .110505E+05    .717272E+08    .248796E+02    .127893E+05        
HST  1ICOFF2   -.239981E+03   -.144069E+04    .134999E+04   -.619964E+01        
HST  1ICOFF3   -.646169E+03    .255458E+03    .157314E+03   -.163699E+03        
HST  1IECOF1    .291083E+02    .343930E+06    .602575E-01    .265822E+02        
HST  1IECOF2    .490782E+02    .344702E+02    .226153E+02    .373901E+02        
HST  1IECOF3    .136656E+02    .173521E+02    .173310E+02    .130859E+02        
HST  1IECOR1 1.000 -.557  .815 -.491 -.808  .929  .729 -.821  .125  .705        
HST  1IECOR2 -.652 -.862 1.000 -.099  .542  .571 -.647 -.048  .589 -.294        
HST  1IECOR3 -.181  .760  .501 1.000 -.569 -.806  .681  .768 -.772 -.175        
HST  1IECOR4  .711 -.426 -.830 1.000  .896 -.450 -.161  .823  .218 -.288        
HST  1IECOR5  .706  .738 1.000 -.706 -.452  .949  .137 -.541  .750  .898        
HST  1IECOR6 1.000  .762 -.707  .299  .693 -.625 -.767 1.000 -.368  .267        
HST  1IECOR7  .773 -.172 -.569 1.000  .279 -.435  .801  .910 1.000  .465        
HST  1IECOR8  .144  .128 1.000 -.049 -.477 1.000  .832 1.000                    
HST  1MNREF     0    1.0000                                                     
HST  1OMEGA     0.0000                                                          
HST  1PHI       0.0000                                                          
HST  1PRCF1     1    9   0.01000                                                
HST  1PRCF11    .000000E+00    .500000E+01    .281732E-01    .712807E-02        
HST  1PRCF12    .000000E+00    .382428E+02    .000000E+00    .000000E+00        
HST  1PRCF13   0.000000E+00                                                     
HST  2  HFIL  6731.dat                                                          
HST  2  HNAM  ROUND ROBIN SAMPLE 4                                              
HST  2  IFIL  I22JAN99.PRM                                                      
HST  2 BANK     2                                                               
HST  2 BIGFO    .619428E+02                                                     
HST  2 CHANS      3360         1      4189 105414034      7550    1             
HST  2 EPHAS    0    0    0    0    0    0    0    0    0    T                  
HST  2 ICONR   5073.42     -1.73      5.11                                      
HST  2 ICONS   5073.42     -1.73      5.11                                      
HST  2 MAXRF   51                                                               
HST  2 NEXC     2                                                               
HST  2 NPHAS    1    1    1    0    0    0    0    0    0                       
HST  2 NREF   469     .5902    Y    Y                                           
HST  2 R-FAC N-obs  468 R-factor  .05646                                        
HST  2 RPOWD     .0523     .0344                                                
HST  2 TRNGE   3.00105  23.99368                                                
HST  2 WREXP     .0371                                                          
HST  2ABSCOR   -.571217E-01    .000000E+00    Y    0    0                       
HST  2BAKGD     7   10    Y    0    Y    0000000000000                          
HST  2BAKGD1    .479570E-01    .406907E-01    .398650E-01    .385313E-01        
HST  2BAKGD2    .487758E-01    .430219E-01    .516786E-01    .502423E-01        
HST  2BAKGD3    .531132E-01    .577525E-01                                      
HST  2BNKNAM  MINUS_153                                                         
HST  2BNKPAR    1.2495  -151.000      25.0     1.321     30.48   16   77        
HST  2BNKTC1 5018.60 5022.60 5026.50 5030.40 5034.30 5038.20 5042.10 5046.00    
HST  2BNKTC2 5049.80 5053.70 5057.50 5061.40 5065.20 5069.00 5072.80 5076.60    
HST  2CHI      90.0000                                                          
HST  2EXC  1      .000     2.999                                                
HST  2EXC  2    24.000  1000.000                                                
HST  2HSCALE     1.0321        Y    0                                           
HST  2I HEAD  CALIBRATION V/NB                                                  
HST  2I ITYP    1    1.0000   23.9997     41946                                 
HST  2ICOFF1    .208819E+01    .161677E+05    .386291E+00    .546976E+05        
HST  2ICOFF2    .645872E-01   -.103173E+05    .652500E-02   -.362341E+05        
HST  2ICOFF3    .311174E-01    .665847E+04    .213234E+00    .000000E+00        
HST  2IECOF1    .155162E+00    .627270E+03    .295853E-02    .541401E+03        
HST  2IECOF2    .488847E-03    .309000E+03    .800190E-04    .155406E+03        
HST  2IECOF3    .112486E-03    .118681E+03    .472194E-02    .000000E+00        
HST  2IECOR1 1.000  .716  .760 -.605  .420  .525  .222 -.456  .012 -.516        
HST  2IECOR2  .048  .000 1.000  .992 -.888  .775  .868  .499 -.718 -.044        
HST  2IECOR3 -.756  .092  .000 1.000 -.871  .720  .827  .444 -.691 -.027        
HST  2IECOR4 -.740  .085  .000 1.000 -.633 -.948 -.285  .423 -.265  .536        
HST  2IECOR5  .038  .000 1.000  .817  .912 -.854 -.288 -.737  .175  .000        
HST  2IECOR6 1.000  .534 -.563  .107 -.606  .025  .000 1.000 -.818 -.422        
HST  2IECOR7 -.613  .208  .000 1.000  .284  .679  .007  .000 1.000  .446        
HST  2IECOR8 -.579  .000 1.000 -.087  .000 1.000  .000  .000                    
HST  2MNREF     0    1.0000                                                     
HST  2OMEGA     0.0000                                                          
HST  2PHI       0.0000                                                          
HST  2PRCF1     1    9   0.01000                                                
HST  2PRCF11    .000000E+00    .500000E+01    .275585E-01    .728077E-02        
HST  2PRCF12    .000000E+00    .730770E+02    .000000E+00    .000000E+00        
HST  2PRCF13   0.000000E+00                                                     
HST  3  HFIL  6731.dat                                                          
HST  3  HNAM  ROUND ROBIN SAMPLE 4                                              
HST  3  IFIL  I22JAN99.PRM                                                      
HST  3 BANK     3                                                               
HST  3 BIGFO    .805620E+02                                                     
HST  3 CHANS      2530         1      5019  86922366      7550    1             
HST  3 EPHAS    0    0    0    0    0    0    0    0    0    T                  
HST  3 ICONR   3817.70     -3.01     -6.00                                      
HST  3 ICONS   3817.70     -3.01     -6.00                                      
HST  3 MAXRF   89                                                               
HST  3 NEXC     2                                                               
HST  3 NPHAS    1    1    1    0    0    0    0    0    0                       
HST  3 NREF   676     .5250    Y    Y                                           
HST  3 R-FAC N-obs  674 R-factor  .06357                                        
HST  3 RPOWD     .0496     .0314                                                
HST  3 TRNGE   1.99878  23.99368                                                
HST  3 WREXP     .0271                                                          
HST  3ABSCOR   -.168159E-02    .000000E+00    Y    0    0                       
HST  3BAKGD     7   10    Y    0    Y    0000000000000                          
HST  3BAKGD1    .398432E-01    .279613E-01    .252806E-01    .321459E-01        
HST  3BAKGD2    .309942E-01    .356101E-01    .359751E-01    .571008E-01        
HST  3BAKGD3    .417539E-01    .338505E-01                                      
HST  3BNKNAM  PLUS_90                                                           
HST  3BNKPAR     1.016      90.0       0.0     1.321     30.48   16   65        
HST  3BNKTC1 3466.60 3490.50 3514.40 3538.20 3562.00 3585.60 3609.20 3632.70    
HST  3BNKTC2 3656.10 3679.40 3702.70 3725.80 3748.90 3772.00 3794.90 3817.70    
HST  3CHI      90.0000                                                          
HST  3EXC  1      .000     1.998                                                
HST  3EXC  2    24.000  1000.000                                                
HST  3HSCALE     1.1860        Y    0                                           
HST  3I HEAD  CALIBRATION V/NB                                                  
HST  3I ITYP    1    1.0000   23.9997     42336                                 
HST  3ICOFF1    .468304E+01    .472700E+05    .409125E+00    .116381E+06        
HST  3ICOFF2    .706951E-01   -.249910E+05    .886590E-02   -.358594E+05        
HST  3ICOFF3    .116236E-01   -.377035E+05    .161391E-01    .000000E+00        
HST  3IECOF1    .172607E+00    .747658E+03    .129637E-02    .155164E+04        
HST  3IECOF2    .204500E-03    .665376E+03    .685466E-04    .428335E+03        
HST  3IECOF3    .108612E-03    .296310E+03    .108900E-03    .000000E+00        
HST  3IECOR1 1.000  .606  .661 -.490 -.001  .455 -.046  .155  .296  .256        
HST  3IECOR2  .154  .000 1.000  .987 -.793  .296  .769  .180  .172  .561        
HST  3IECOR3  .441  .335  .000 1.000 -.788  .208  .755  .103  .194  .532        
HST  3IECOR4  .430  .306  .000 1.000  .127 -.991  .146 -.629 -.472 -.528        
HST  3IECOR5  .115  .000 1.000 -.100  .941 -.569  .399  .092  .642  .000        
HST  3IECOR6 1.000 -.141  .644  .414  .480 -.143  .000 1.000 -.528  .495        
HST  3IECOR7  .189  .587  .000 1.000 -.250 -.139 -.802  .000 1.000  .901        
HST  3IECOR8  .580  .000 1.000  .466  .000 1.000  .000  .000                    
HST  3MNREF     0    1.0000                                                     
HST  3OMEGA     0.0000                                                          
HST  3PHI       0.0000                                                          
HST  3PRCF1     1    9   0.01000                                                
HST  3PRCF11    .000000E+00    .500000E+01    .288849E-01    .351727E-02        
HST  3PRCF12    .000000E+00    .886754E+02    .000000E+00    .000000E+00        
HST  3PRCF13   0.000000E+00                                                     
HST  4  HFIL  6731.dat                                                          
HST  4  HNAM  ROUND ROBIN SAMPLE 4                                              
HST  4  IFIL  I22JAN99.PRM                                                      
HST  4 BANK     4                                                               
HST  4 BIGFO    .684510E+02                                                     
HST  4 CHANS      2532         1      5017 192056456      7550    1             
HST  4 EPHAS    0    0    0    0    0    0    0    0    0    T                  
HST  4 ICONR   3807.24     -1.77      1.17                                      
HST  4 ICONS   3807.24     -1.77      1.17                                      
HST  4 MAXRF   61                                                               
HST  4 NEXC     2                                                               
HST  4 NPHAS    1    1    1    0    0    0    0    0    0                       
HST  4 NREF   642     .5249    Y    Y                                           
HST  4 R-FAC N-obs  641 R-factor  .07264                                        
HST  4 RPOWD     .0480     .0319                                                
HST  4 TRNGE   2.00070  23.99368                                                
HST  4 WREXP     .0253                                                          
HST  4ABSCOR   -.134328E-01    .000000E+00    Y    0    0                       
HST  4BAKGD     7   10    Y    0    Y    0000000000000                          
HST  4BAKGD1    .444366E-01    .297374E-01    .243856E-01    .297200E-01        
HST  4BAKGD2    .279389E-01    .302408E-01    .315988E-01    .442399E-01        
HST  4BAKGD3    .328840E-01    .356439E-01                                      
HST  4BNKNAM  MINUS_90                                                          
HST  4BNKPAR     1.016    -90.00       0.0     1.321     30.48   16   69        
HST  4BNKTC1 3811.10 3788.50 3765.70 3742.80 3719.70 3696.50 3673.20 3649.70    
HST  4BNKTC2 3626.10 3602.30 3578.40 3554.30 3530.10 3505.80 3481.30 3456.70    
HST  4CHI      90.0000                                                          
HST  4EXC  1      .000     1.999                                                
HST  4EXC  2    24.000  1000.000                                                
HST  4HSCALE     1.1340        Y    0                                           
HST  4I HEAD  CALIBRATION V/NB                                                  
HST  4I ITYP    1    1.0000   23.9997     44263                                 
HST  4ICOFF1    .553744E+01    .435359E+05    .384803E+00    .114387E+06        
HST  4ICOFF2    .659711E-01   -.228667E+05    .791199E-02   -.350288E+05        
HST  4ICOFF3    .120252E-01   -.380769E+05    .160239E-01    .000000E+00        
HST  4IECOF1    .210867E+00    .649651E+03    .119295E-02    .132249E+04        
HST  4IECOF2    .193978E-03    .580624E+03    .631571E-04    .408420E+03        
HST  4IECOF3    .112617E-03    .302003E+03    .104215E-03    .000000E+00        
HST  4IECOR1 1.000  .646  .703 -.497  .041  .460 -.056  .053  .335  .257        
HST  4IECOR2  .212  .000 1.000  .987 -.745  .357  .728  .169 -.018  .572        
HST  4IECOR3  .411  .411  .000 1.000 -.744  .270  .716  .094  .012  .549        
HST  4IECOR4  .402  .381  .000 1.000  .141 -.991  .249 -.504 -.536 -.507        
HST  4IECOR5  .073  .000 1.000 -.090  .945 -.632  .313  .082  .646  .000        
HST  4IECOR6 1.000 -.214  .509  .495  .469 -.084  .000 1.000 -.636  .344        
HST  4IECOR7  .117  .592  .000 1.000 -.321 -.297 -.849  .000 1.000  .922        
HST  4IECOR8  .553  .000 1.000  .512  .000 1.000  .000  .000                    
HST  4MNREF     0    1.0000                                                     
HST  4OMEGA     0.0000                                                          
HST  4PHI       0.0000                                                          
HST  4PRCF1     1    9   0.01000                                                
HST  4PRCF11    .000000E+00    .500000E+01    .286571E-01    .123176E-01        
HST  4PRCF12    .000000E+00    .181839E+03    .000000E+00    .000000E+00        
HST  4PRCF13   0.000000E+00                                                     
LEQV PSFR       3    1    1    1                                                
LEQV PSFR 11  1,ALL         1.000                                               
LEQV PSFR 21  2,ALL         1.000                                               
LEQV PSFR 31  3,ALL         1.000                                               
ZZZZZZZZZZZZ  Last EXP file record                                              
    HSTRY  7 GENLES  MS-DOS 1999-01-29T08:39:56  Sdsq=  .524E+05 S/E=  .442     
