      SUBROUTINE HEAD4
      COMMON /UNIT2/ IUNITB
C
C
C     SUBROUTINE 'HEAD4' ...
C        WRITE SHORT DESCRIPTION OF PROGRAM OUTPUT
C        INV FUNCTION (MATRIX INVERSION)
C
C
C     --- WRITE HEADING FOR OUTPUT
      WRITE(IUNITB,6100)
      WRITE(IUNITB,6110)
      WRITE(IUNITB,6120)
      WRITE(IUNITB,9020)
      RETURN
 6100 FORMAT(21X,'** MATRIX INVERSION **'/)
 6110 FORMAT(7X,'    T 2      =   Input transformation matrix.')
 6120 FORMAT(7X,'    T 2 INV  =   Inverse matrix for T 2.')
 9020 FORMAT(//)
      END
