      SUBROUTINE SET
      COMMON /MATR1/ U1,V1,W1,U2,V2,W2,U3,V3,W3
      COMMON /MATR2/ U(9),T(9)
C
C
C     SUBROUTINE 'SET' ...
C        PREPARE TO UPDATE THE TOTAL TRANSFORMATION MATRIX
C        (U1,V1,W1,U2,V2,W2,U3,V3,W3) BY MATRIX MULTIPLICATION
C
C
C     --- SAVE THE CURRENT VALUES OF THE ELEMENTS FOR THE TOTAL
C         TRANSFORMATION MATRIX IN THE ARRAY T AND SET THE MATRIX
C         ELEMENTS IN THE UPDATE MATRIX U TO ZERO
      T(1) = U1
      T(2) = V1
      T(3) = W1
      T(4) = U2
      T(5) = V2
      T(6) = W2
      T(7) = U3
      T(8) = V3
      T(9) = W3
      DO 100 I = 1,9
         U(I) = 0.0
  100 CONTINUE
      RETURN
      END
