# -*- coding: utf-8 -*-
# git_verinfo.py - GSAS-II version info from git
# Do not edit, generated by '/Users/toby/git/GSASII/GSASII/install/git_filters.py --record-version' command
# Created 2024-04-03 21:47:10.108677-05:00

git_version = 'df4c406d3dd5dec6d6293bfed252b979476cefb0'
git_tags = ['5774']
git_prevtaggedversion = 'c5a84c527926d3213aedd59bac16c6ce0a96482e'
git_prevtags = ['5773']
