# -*- coding: utf-8 -*-
# git_verinfo.py - GSAS-II version info from git
# Do not edit, generated by 'install/incr-version.py minor' script
# Created 2026-01-25 16:31:02.749193-06:00

git_version = 'a573b7e4eebef709cdddbcc4e59ae0da470ef3af'
git_tags = ['5829']
git_prevtaggedversion = '9e0a3d051658de404ae6cb50352f2602d2f4b146'
git_prevtags = ['5828']
git_versiontag = 'v5.7.0'
