# -*- coding: utf-8 -*-
# git_verinfo.py - GSAS-II version info from git
# Do not edit, generated by '/Users/toby/G2/git/GSASII/GSASII/install/git_filters.py --record-version' command
# Created 2024-10-06 12:57:47.333173-05:00

git_version = 'e7be4c85e5743809932a0e53f726f2e8424edf90'
git_tags = ['5798']
git_prevtaggedversion = 'b4d1879f1c2288a8990d96c6b448b77e94ccc102'
git_prevtags = ['5797']
