     VERSION    6     Wed Nov 10 14:42:34 2010                                  
      DESCR   garnet                                                            
    HSTRY  1 EXPEDT  Win32  Nov 09 14:47:58 2011 P PH        LA                 
    HSTRY  2 EXPEDT  Win32  Nov 09 14:49:34 2011             L   O              
    HSTRY  3 POWPREF Win32  Nov 09 14:49:38 2011                                
    HSTRY  4 GENLES  Win32  Nov 09 14:49:41 2011 Sdsq= 0.461E+06 S/E= 0.114E-06 
    HSTRY  5 EXPEDT  Win32  Nov 09 14:50:12 2011             L   O              
    HSTRY  6 GENLES  Win32  Nov 09 14:50:16 2011 Sdsq= 0.661E+05 S/E=  10.5     
    HSTRY  7 EXPEDT  Win32  Nov 09 14:53:14 2011             LA  O              
    HSTRY  8 GENLES  Win32  Nov 09 14:53:18 2011 Sdsq= 0.169E+05 S/E=  268.     
    HSTRY  9 EXPEDT  Win32  Nov 09 14:55:49 2011             L  LO              
    HSTRY 10 GENLES  Win32  Nov 09 14:55:52 2011 Sdsq= 0.113E+05 S/E= 0.277     
    HSTRY 11 GENLES  Win32  Nov 30 11:34:00 2011 Sdsq= 0.113E+05 S/E= 0.265     
    HSTRY 12 EXPEDT  Win32  Mar 05 09:12:00 2012             LA                 
  DSGL CDAT1  DRAD ARAD NOFO                                                    
  GNLS  RUN on Nov 30 11:34:00 2011    Total cycles run  18       11275.        
  GNLS CDAT1  MXCY  5                                                           
  GNLS SHFTS      0.51      0.03                                                
 AFAC  O     3.048513.2771 2.2868 5.7011 1.5463  .3239  .867032.9089  .2508 RHF 
 AFAC  O_    15.999 .5805      .00019                                           
 AFAC  O_SIZ      1.09      0.89 1.45   96 1.40                                 
 AFAC  O_XAB  988.0 590.6 293.1 30.48 17.21 1730. 478.0                         
 AFAC  O_XF1  0.093 0.072 0.049 0.011 0.006 0.121 0.063-0.002-0.003-0.003       
 AFAC  O_XF2  0.073 0.052 0.032 0.006 0.004 0.106 0.044 0.000 0.000 0.000       
 AFAC  Y    17.77601.4029010.294612.80065.72629.1255993.26588104.3541.91213*RHF 
 AFAC  Y   M  .5915 67.608 1.5123 17.900-1.1130 14.136  .0000   .000  .0080     
 AFAC  Y   N14.4084 44.658 5.1045 14.904 -.0535  3.319  .0000   .000  .0028 2.00
 AFAC  Y_    88.907  .775        1.28                                           
 AFAC  Y_SIZ      2.00      1.80 2.25  007                                      
 AFAC  Y_XAB  54450 34730 18760 14400  7817 85600 27300                         
 AFAC  Y_XF1  0.126 0.014-0.267-2.796-0.288 0.065-0.072 0.138 0.128 0.082       
 AFAC  Y_XF2  3.996 3.005 2.024 3.567 2.410 5.420 2.624 0.439 0.413 0.311       
 AFAC AL     6.4202 3.0387 1.9002  .7426 1.593631.5472 1.964685.0886 1.1151 RHF 
 AFAC AL_    26.982 .3449        .231                                           
 AFAC AL_SIZ      1.60      1.43 2.05  109                                      
 AFAC AL_XAB   7074  4368  2249 225.8 113.7 11600 3420.                         
 AFAC AL_XF1  0.326 0.277 0.213 0.064 0.041 0.376 0.255-0.002-0.003-0.005       
 AFAC AL_XF2  0.521 0.381 0.246 0.051 0.031 0.729 0.328 0.004 0.004 0.003       
 AFAC FE    11.7695 4.7611 7.3573  .3072 3.522215.3535 2.304576.8805 1.0369 RHF 
 AFAC FE   M  .0706 35.008  .3589 15.358  .5819  5.561  .0000   .000 -.0114     
 AFAC FE   N 1.9405 18.473 1.9566  6.323  .5166  2.161  .0000   .000  .0036 2.00
 AFAC FE_    55.847  .945        2.56                                           
 AFAC FE_SIZ      1.47      1.27 2.15   32                                      
 AFAC FE_XAB  10490  6528 28230  3500  1791 17200 5310.                         
 AFAC FE_XF1 -1.294-2.055-1.134 0.346 0.289-0.890-3.331 0.044 0.039 0.017       
 AFAC FE_XF2  0.762 0.565 3.197 0.844 0.545 1.052 0.490 0.084 0.079 0.058       
 EXPR  HTYP1  PNC                                                               
 EXPR  NATYP    4                                                               
 EXPR  NHST     1                                                               
 EXPR ATYP 1  Y           1      2.00      1.80 2.25  007                       
 EXPR ATYP 2  FE          2      1.47      1.27 2.15   32                       
 EXPR ATYP 3  AL          2      1.60      1.43 2.05  109                       
 EXPR ATYP 4  O           1      1.09      0.89 1.45   96 1.40                  
 EXPR NPHAS     1    0    0    0    0    0    0    0    0                       
 REFN GDNFT  Reduced CHI**2 =  4.250     for   19 variables                     
 REFN RPOWD     0.0549    0.0407   2672  11275.        0.0000    0.0000     0   
 REFN STATS  Cycle  18 There were  2672 observations. Total CHI**2 = 1.1275E+04 
CRS1    PNAM  garnet                                                            
CRS1   NATOM    6                                                               
CRS1  ABC    12.187720 12.187720 12.187720    Y    0                            
CRS1  ABCSIG  0.000650  0.000650  0.000650                                      
CRS1  ANGLES   90.0000   90.0000   90.0000                                      
CRS1  ANGSIG    0.0000    0.0000    0.0000                                      
CRS1  AT  1A  Y         0.125000  0.000000  0.250000  1.000000Y1        24 000  
CRS1  AT  1B  0.007186                                                    I  U  
CRS1  AT  2A  FE        0.000000  0.000000  0.000000  0.728206FE2       16 000  
CRS1  AT  2B  0.005753                                                    IF U  
CRS1  AT  3A  AL        0.000000  0.000000  0.000000  0.000000AL3       16 000  
CRS1  AT  3B  0.025000                                                    I     
CRS1  AT  4A  AL        0.375000  0.000000  0.250000  1.516663AL4       24 000  
CRS1  AT  4B  0.002948                                                    IF U  
CRS1  AT  5A  FE        0.375000  0.000000  0.250000  0.000000FE5       24 000  
CRS1  AT  5B  0.025000                                                    I     
CRS1  AT  6A  O        -0.029366  0.053912  0.150731  1.000000O6        96 000  
CRS1  AT  6B  0.008330                                                    I XU  
CRS1  CELVOL       1810.370          0.290                                      
CRS1  CHMF 1  Y             1.50                                                
CRS1  CHMF 2  FE            0.73                                                
CRS1  CHMF 3  AL            2.27                                                
CRS1  CHMF 4  O             6.00                                                
CRS1  SG SYM  I a 3 d                                                           
CRS1  SPAXIS    0    0    1                                                     
HAP1 1 ZONE     0    0    0    0                                                
HAP1 1EXTPOW    0.00000E+00    N    0                                           
HAP1 1NAXIS     1                                                               
HAP1 1PHSFR      1.0000        N    0                                           
HAP1 1PRCF      3   19   0.01000    0YYYNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN       
HAP1 1PRCF 1   0.253190E+03  -0.560024E+03   0.549307E+03   0.000000E+00        
HAP1 1PRCF 2   0.000000E+00   0.000000E+00   0.100000E+00   0.100000E-01        
HAP1 1PRCF 3   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 4   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HAP1 1PRCF 5   0.000000E+00   0.000000E+00   0.000000E+00                       
HAP1 1PREFO1  1.000000  1.000000  0.000000  0.000000  1.000000   NN    0    0   
HAP1 1RADDAM    0.00000E+00    N    0      0.00                                 
HST  1  HFIL  C:\gsas\example\garnet.raw                                        
HST  1  HNAM  Y3FE2(ALO4)3 RT 1.909                                             
HST  1  IFIL  C:\gsas\example\inst_d1a.prm                                      
HST  1 BANK     1                                                               
HST  1 BIGFO   0.886618E+06                                                     
HST  1 CHANS         0         1      2673  83972096      2679    0    0        
HST  1 EPHAS    0    0    0    0    0    0    0    0    0    Y                  
HST  1 ICONR  1.909000  0.000000      -7.3         0       0.0    0             
HST  1 ICONS 1.9090000 0.0000000   4.86386    Z    0   0.00000    0   0.50000   
HST  1 MAXRF    5                                                               
HST  1 NEXC     2                                                               
HST  1 NFOBS   91    0    0    0    0    0    0    0    0                       
HST  1 NPHAS    1    0    0    0    0    0    0    0    0                       
HST  1 NREF    92    0.9729    Y    Y                                           
HST  1 R-FAC   91   0.22579   1.290179E+07                                      
HST  1 RPOWD    0.0549    0.0407   2672  11275.        0.0000    0.0000    0    
HST  1 TRNGE  24.00000 157.60001                                                
HST  1 WREXP    0.0267                                                          
HST  1ABSCOR   0.000000E+00   0.000000E+00    N    0                            
HST  1BAKGD     2    3    Y    0    Y                                           
HST  1BAKGD1   0.141481E+03   0.202892E+02   0.112945E+02                       
HST  1CHI      90.0000                                                          
HST  1DETAZM    0.0000                                                          
HST  1EXC  1     0.000     0.000                                                
HST  1EXC  2   157.600  1000.000                                                
HST  1EXMNMX   1.00000   1.00000                                                
HST  1HSCALE     3060.4        Y    0                                           
HST  1I HEAD  DUMMY INCIDENT SPECTRUM FOR DIFFRACTOMETER D1A                    
HST  1I ITYP    0    0.0000  180.0000         1                                 
HST  1MNREF     0    1.0000                                                     
HST  1ODMNMX   1.00000   1.00000                                                
HST  1OMEGA     0.0000                                                          
HST  1PHI       0.0000                                                          
HST  1PRCF1     1    6      0.01                                                
HST  1PRCF11   0.354031E+03  -0.760404E+03   0.651592E+03   0.000000E+00        
HST  1PRCF12   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00        
HST  1PRCF2     2    6      0.01                                                
HST  1PRCF21   0.354031E+03  -0.760404E+03   0.651592E+03   0.000000E+00        
HST  1PRCF22   0.000000E+00   0.000000E+00                                      
HST  1RSP    0.0581 0.0459 0.0332 0.0242 0.0274 0.0366 0.0362 0.0381 0.0000     
HST  1RSPA   0.0524 0.0368 0.0242 0.0167 0.0187 0.0290 0.0273 0.0341 0.0000     
HST  1RSPTT  24.00 38.80 53.65 68.50 83.35 98.20113.05127.90142.75  0.00        
HST  1RSPW   0.0736 0.0629 0.0538 0.0444 0.0393 0.0678 0.0545 0.0480 0.0000     
HST  1RSPWA  0.0475 0.0413 0.0314 0.0256 0.0220 0.0538 0.0363 0.0378 0.0000     
HST  1TRMNMX   1.00000   1.00000                                                
LNCN   1   1  1  2UISO  1.00001  3UISO  1.0000                                  
ZZZZZZZZZZZZ  Last EXP file record                                              
