py.install_sources([
    '__init__.py',
    '_paths.py',
    '_web.py',
    'app.py',
    'cli.py',
    'gui.py',
    'ingest.py',
    'rag.py',
    'sources.py',
],
  pure: false,    # Will be installed next to binaries
  subdir: 'GSASII/gsas_query'  # Folder relative to site-packages to install to
)
