channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - scipy
  - pyopengl
  - imageio
  - h5py
  - numpy
  - sphinx-rtd-theme
#  - sphinx # included by RTD
#  - pillow # included by RTD
  - pip
  - matplotlib
  - wxpython
  - gitpython
  - pytest
